// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }

//.............

// import { Poppins } from "next/font/google";
// import "./globals.scss";

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: [
//     "100",
//     "200",
//     "300",
//     "400",
//     "500",
//     "600",
//     "700",
//     "800",
//     "900",
//   ],
//   variable: "--font-poppins", // optional but recommended
// });

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className={poppins.variable}>
//       <body>{children}</body>
//     </html>
//   );
// }
//...........................

"use client";

import { useEffect, useState } from "react";
import { Poppins } from "next/font/google";
import "./globals.scss";
import Loader from "@/components/Loader";
import CustomCursor from "@/components/CustomCursor/CustomCursor";
import ScrollToTop from "@/components/ScrollTop";
import WhatsAppButton from "@/components/Wtsapp";
import Twobuttons from "@/components/Twobuttons";
import RouteScrollReset from "@/components/RouteScrollReset";

const poppins = Poppins({
  subsets: ["latin"],
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
  ],
  variable: "--font-poppins",
});

export default function RootLayout({ children }) {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => {
      setLoading(false);
    }, 1500); // ⏱ loader duration

    return () => clearTimeout(timer);
  }, []);

  return (
    <html lang="en" className={poppins.variable}>
      <body>
        <CustomCursor/>
        {loading && <Loader />}
        {!loading && children}
        {/* <ScrollToTop />
         <WhatsAppButton /> */}
         <RouteScrollReset />
         <Twobuttons/>
      </body>
    </html>
  );
}
